FROM jenkins:1.0.18
USER jenkins 
RUN cd /var/jenkins_home && gh repo clone nir-adler/devops-test
USER root
RUN apt update -y
RUN apt install cron -y
RUN cron
COPY ./sync-github-devops-test-repo.sh /sync-github-devops-test-repo.sh
COPY ./files/jenkins.sh /usr/local/bin/jenkins.sh
RUN chown  jenkins:jenkins /sync-github-devops-test-repo.sh
RUN chown  root:root /usr/local/bin/jenkins.sh
RUN apt -y install systemctl
RUN systemctl is-enabled cron
RUN  chmod u+s /usr/sbin/cron
USER jenkins 
RUN cd /var/jenkins_home && echo "* * * * * (/sync-github-devops-test-repo.sh)" >> mycron
RUN cd /var/jenkins_home && echo "* * * * * (sleep 10 ; /sync-github-devops-test-repo.sh)" >> mycron
RUN cd /var/jenkins_home && echo "* * * * * (sleep 20 ; /sync-github-devops-test-repo.sh)" >> mycron
RUN cd /var/jenkins_home && echo "* * * * * (sleep 30 ; /sync-github-devops-test-repo.sh)" >> mycron
RUN cd /var/jenkins_home && echo "* * * * * (sleep 40 ; /sync-github-devops-test-repo.sh)" >> mycron
RUN cd /var/jenkins_home && echo "* * * * * (sleep 50 ; /sync-github-devops-test-repo.sh)" >> mycron
RUN cd /var/jenkins_home && crontab mycron
RUN crontab -l

