version: '3.6'

services:
  jenkins:
    hostname: jenkins
    container_name: jenkins
    image: jenkins:1.0.25  
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
      - 2376:2376
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2376
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
networks:
  jenkins: